### ISSUE TITLE
Unusable when pixelRatio is not an integer

### ISSUE THREAD

**Issue by xmcp** [zhw2590582/WFPlayer#1]
Step to reproduce:

1. Change display scaling rate to 1.25x.
2. Open https://wfplayer.js.org/
3. The waveform doesn't load, and console shows this exception:

```
Uncaught WFPlayerError: pixelRatio expect a positive integer greater than or equal to 1, but got 1.25.
    at errorHandle (https://wfplayer.js.org/uncompiled/wfplayer.js:398:13)
    at https://wfplayer.js.org/uncompiled/wfplayer.js:1592:13
    at y (https://wfplayer.js.org/uncompiled/wfplayer.js:138:3586)
    at https://wfplayer.js.org/uncompiled/wfplayer.js:138:2947
    at Array.forEach (<anonymous>)
    at https://wfplayer.js.org/uncompiled/wfplayer.js:138:2878
    at f (https://wfplayer.js.org/uncompiled/wfplayer.js:138:3207)
    at WFPlayer.setOptions (https://wfplayer.js.org/uncompiled/wfplayer.js:1669:24)
    at new WFPlayer (https://wfplayer.js.org/uncompiled/wfplayer.js:1641:13)
    at initWFPlayer (https://wfplayer.js.org/assets/js/index.js:28:10)
```

**Comment by zhw2590582** [comment]
Thanks, that this issue will be fixed in the next minor update.
